# 文件1的数据
realms = [
    ["燃烧之刃", "埃霍恩", "格瑞姆巴托"],
    ["白银之手"],
    ["死亡之翼"],
    ["安苏"],
    ["托塞德林", "凤凰之神"],
    ["霍格", "主宰之剑"],
    ["霜之哀伤", "回音山", "遗忘海岸", "神圣之歌"],
    ["影之哀伤"],
    ["血色十字军"],
    ["罗宁"],
    ["伊森利恩"],
    ["贫瘠之地"],
    ["米奈希尔", "无尽之海"],
    ["熊猫酒仙"],
    ["国王之谷"],
    ["末日行者"],
    ["亡语者", "克尔苏加德", "奥尔加隆"],
    ["冰风岗"],
    ["洛肯", "海克泰尔"],
    ["金色平原"],
    ["诺兹多姆", "梦境之树", "泰兰德"],
    ["布兰卡德"],
    ["奥特兰克"],
    ["迦拉克隆"],
    ["埃德萨拉"],
    ["卡扎克", "巴纳扎尔", "爱斯特纳", "戈古纳斯", "红云台地", "激流之傲", "拉格纳罗斯", "龙骨平原"],
    ["沙怒", "血羽", "森金", "戈提克", "雏龙之翼", "法拉希姆", "玛法里奥", "玛维·影歌", "天空之墙"],
    ["迅捷微风", "萨洛拉丝"],
    ["塞拉摩", "麦姆", "暗影迷宫"],
    ["黑铁"],
    ["丽丽（四川）"],
    ["鬼雾峰", "黑暗之矛", "塞泰克", "罗曼斯", "巨龙之吼", "黑石尖塔"],
    ["安戈洛", "德拉诺", "深渊之喉", "古拉巴什", "深渊之巢", "外域", "阿格拉玛", "织亡者", "屠魔山谷"],
    ["祖尔金", "破碎岭", "厄祖玛特", "奎尔萨拉斯", "埃基尔松"],
    ["暴风祭坛", "摩摩尔", "熵魔", "利刃之拳", "黑翼之巢", "玛里苟斯", "艾萨拉"],
    ["索瑞森", "试炼之环", "尘风峡谷", "伊利丹"],
    ["雷克萨", "火喉", "激流堡", "阿古斯"],
    ["库德兰", "加里索斯", "红龙军团", "山丘之王", "拉文霍德"],
    ["提尔之手", "萨菲隆", "灰谷", "布莱克摩", "大漩涡", "风暴之怒"],
    ["卡珊德拉", "暗影之月"],
    ["亚雷戈斯", "银松森林"],
    ["伊瑟拉", "轻风之语", "月神殿", "艾森娜"],
    ["狂热之刃"],
    ["朵丹尼尔", "蓝龙军团", "芬里斯", "希雷诺斯", "烈焰荆棘", "天谴之门", "沃金"],
    ["达克萨隆", "阿纳克洛斯"],
    ["埃雷达尔", "永恒之井"],
    ["菲拉斯", "奈萨里奥", "红龙女王", "格雷迈恩", "黑手军团", "瓦丝琪"],
    ["勇士岛", "达文格尔", "索拉丁", "雷霆之王"],
    ["斩魔者", "鲜血熔炉", "埃加洛尔", "幽暗沼泽"],
    ["黑锋哨站", "熔火之心"],
    ["安格博达", "冰霜之刃"],
    ["麦迪文", "月光林地"],
    ["风暴之鳞", "耐普图隆", "日落沼泽", "安纳塞隆"],
    ["血环", "范克里夫"],
    ["奥蕾莉亚", "万色星辰", "世界之树", "布莱恩"],
    ["迪瑟洛克", "拉文凯斯", "加兹鲁维", "哈兰", "奥金顿"],
    ["图拉扬", "塞纳留斯", "瓦里玛萨斯", "海达希亚"],
    ["永夜港", "黄金之路", "翡翠梦境"],
    ["银月", "羽月", "耳语海岸", "玛多兰"],
    ["雷斧堡垒"],
    ["艾维娜", "艾露恩"],
    ["诺莫瑞根", "刀塔", "无底海渊", "阿努巴拉克", "达隆米尔", "自由之风", "艾欧娜尔", "冬寒"],
    ["诺森德", "死亡熔炉", "哈卡", "燃烧军团"],
    ["恶魔之魂", "希尔瓦娜斯", "大地之怒"],
    ["伊森德雷", "雷霆之怒", "达斯雷玛", "库尔提拉斯"],
    ["加基森", "黑暗虚空"],
    ["燃烧平原", "风行者"],
    ["铜龙军团", "普罗德摩", "玛洛加尔"],
    ["古加尔", "洛丹伦"],
    ["巫妖之王", "基尔罗格", "迦顿"],
    ["藏宝海湾", "塔伦米尔", "阿拉希"],
    ["烈焰峰", "瓦拉斯塔兹"],
    ["寒冰皇冠", "冬泉谷"],
    ["提瑞斯法", "暗影议会"],
    ["苏塔恩", "卡拉赞"],
    ["阿拉索", "阿迦玛甘"],
    ["白骨荒野", "能源舰", "刺骨利刃", "千针石林"],
    ["凯恩血蹄", "卡德加", "瑟莱德丝"],
    ["洛萨", "阿卡玛", "萨格拉斯"],
    ["密林游侠", "巴瑟拉斯", "塔纳利斯"],
    ["通灵学院", "恶魔之翼"],
    ["血吼", "黑暗之门"],
    ["加尔", "黑龙军团"],
    ["守护之剑", "瑞文戴尔"],
    ["嚎风峡湾", "闪电之刃"],
    ["恐怖图腾", "伊兰尼库斯", "阿克蒙德"],
    ["阿尔萨斯", "祖达克"],
    ["霜狼", "迦玛兰"],
    ["杜隆坦", "狂风峭壁", "玛瑟里顿", "暮色森林"],
    ["阿曼尼", "地狱咆哮", "奈法利安"],
    ["耐奥祖", "地狱之石", "火焰之树"],
    ["达尔坎", "鹰巢山", "石锤", "范达尔鹿盔"],
    ["奥斯里安", "战歌", "夺灵者"],
    ["符文图腾", "黑暗魅影", "卡德罗斯", "阿斯塔洛"],
    ["圣火神殿", "桑德兰"],
    ["古尔丹", "血顶"],
    ["阿扎达斯", "石爪峰"],
    ["基尔加丹", "奥拉基尔"],
    ["玛诺洛斯", "达纳斯", "火烟之谷"],
    ["萨尔", "伊莫塔尔"],
    ["奥妮克希亚", "海加尔", "纳克萨玛斯"],
    ["艾莫莉丝", "奎尔丹纳斯", "布鲁塔卢斯"],
    ["蜘蛛王国"],
    ["影牙要塞", "艾苏恩"],
    ["斯坦索姆", "泰拉尔", "穆戈尔", "格鲁尔"],
    ["荆棘谷", "拉贾克斯"],
    ["凯尔萨斯", "双子峰", "冰川之拳", "埃苏雷格"],
    ["菲米丝", "元素之力", "夏维安"],
    ["塞拉赞恩", "太阳之井"],
    ["古达克", "梅尔加尼"],
    ["伊萨里奥斯", "祖阿曼"],
    ["风暴之眼", "雷霆号角"],
    ["盖斯", "安其拉", "弗塞雷迦"],
    ["晴日峰（江苏）"],
    ["奥达曼", "甜水绿洲"],
    ["奥杜尔", "逐日者", "普瑞斯托"],
    ["血牙魔王", "埃克索图斯"],
    ["风暴峭壁"],
    ["火羽山", "迦罗娜", "纳沙塔尔", "末日祷告祭坛"],
    ["时光之穴"],
    ["斯克提斯"],
    ["巴尔古恩", "托尔巴拉德"],
    ["壁炉谷"],
    ["金度", "克洛玛古斯"],
    ["安加萨", "莱索恩"],
    ["丹莫德", "克苏恩"],
    ["冬拥湖", "迪托马斯", "达基萨斯"],
    ["阿比迪斯", "踏梦者"],
    ["兰娜瑟尔", "毁灭之锤"],
    ["扎拉赞恩", "安威玛尔"],
    ["安东尼达斯"],
    ["瓦里安"],
    ["生态船", "军团要塞"],
    ["远古海滩"],
    ["苏拉玛"],
    ["辛达苟萨", "暗影裂口"],
    ["瓦拉纳"],
]

# 文件2的数据
realmData = {
    700: {"name": "阿格拉玛", "connected": []},
    700:{"name":"阿格拉玛", "connected":[]},
    703:{"name":"艾苏恩", "connected":[]},
    704:{"name":"安威玛尔", "connected":[]},
    705:{"name":"奥达曼", "connected":[]},
    706:{"name":"奥蕾莉亚", "connected":[]},
    707:{"name":"白银之手", "connected":[]},
    708:{"name":"暴风祭坛", "connected":[]},
    709:{"name":"藏宝海湾", "connected":[]},
    710:{"name":"尘风峡谷", "connected":[]},
    711:{"name":"达纳斯", "connected":[]},
    712:{"name":"迪托马斯", "connected":[]},
    714:{"name":"国王之谷", "connected":[]},
    715:{"name":"黑龙军团", "connected":[]},
    716:{"name":"黑石尖塔", "connected":[]},
    717:{"name":"红龙军团", "connected":[]},
    718:{"name":"回音山", "connected":[]},
    719:{"name":"基尔罗格", "connected":[]},
    720:{"name":"卡德罗斯", "connected":[]},
    721:{"name":"卡扎克", "connected":[]},
    723:{"name":"库德兰", "connected":[]},
    725:{"name":"蓝龙军团", "connected":[]},
    726:{"name":"雷霆之王", "connected":[]},
    727:{"name":"烈焰峰", "connected":[]},
    729:{"name":"罗宁", "connected":[]},
    730:{"name":"洛萨", "connected":[]},
    731:{"name":"玛多兰", "connected":[]},
    732:{"name":"玛瑟里顿", "connected":[]},
    734:{"name":"奈萨里奥", "connected":[]},
    736:{"name":"诺莫瑞根", "connected":[]},
    737:{"name":"普瑞斯托", "connected":[]},
    738:{"name":"燃烧平原", "connected":[]},
    739:{"name":"萨格拉斯", "connected":[]},
    740:{"name":"山丘之王", "connected":[]},
    741:{"name":"死亡之翼", "connected":[]},
    742:{"name":"索拉丁", "connected":[]},
    743:{"name":"索瑞森", "connected":[]},
    744:{"name":"铜龙军团", "connected":[]},
    745:{"name":"图拉扬", "connected":[]},
    746:{"name":"伊瑟拉", "connected":[]},
    748:{"name":"阿迦玛甘", "connected":[]},
    749:{"name":"阿克蒙德", "connected":[]},
    750:{"name":"埃加洛尔", "connected":[]},
    751:{"name":"埃苏雷格", "connected":[]},
    753:{"name":"艾萨拉", "connected":[]},
    754:{"name":"艾森娜", "connected":[]},
    755:{"name":"爱斯特纳", "connected":[]},
    756:{"name":"暗影之月", "connected":[]},
    757:{"name":"奥拉基尔", "connected":[]},
    758:{"name":"冰霜之刃", "connected":[]},
    760:{"name":"达斯雷玛", "connected":[]},
    761:{"name":"地狱咆哮", "connected":[]},
    762:{"name":"地狱之石", "connected":[]},
    764:{"name":"风暴之怒", "connected":[]},
    765:{"name":"风行者", "connected":[]},
    766:{"name":"弗塞雷迦", "connected":[]},
    767:{"name":"戈古纳斯", "connected":[]},
    768:{"name":"海加尔", "connected":[]},
    769:{"name":"毁灭之锤", "connected":[]},
    770:{"name":"火焰之树", "connected":[]},
    771:{"name":"卡德加", "connected":[]},
    772:{"name":"拉文凯斯", "connected":[]},
    773:{"name":"玛法里奥", "connected":[]},
    774:{"name":"玛维·影歌", "connected":[]},
    775:{"name":"梅尔加尼", "connected":[]},
    776:{"name":"梦境之树", "connected":[]},
    778:{"name":"耐普图隆", "connected":[]},
    780:{"name":"轻风之语", "connected":[]},
    781:{"name":"夏维安", "connected":[]},
    782:{"name":"塞纳留斯", "connected":[]},
    784:{"name":"闪电之刃", "connected":[]},
    786:{"name":"石爪峰", "connected":[]},
    787:{"name":"泰兰德", "connected":[]},
    788:{"name":"屠魔山谷", "connected":[]},
    790:{"name":"伊利丹", "connected":[]},
    791:{"name":"月光林地", "connected":[]},
    792:{"name":"月神殿", "connected":[]},
    793:{"name":"战歌", "connected":[]},
    794:{"name":"主宰之剑", "connected":[]},
    797:{"name":"埃德萨拉", "connected":[]},
    799:{"name":"血环", "connected":[]},
    800:{"name":"布莱克摩", "connected":[]},
    802:{"name":"杜隆坦", "connected":[]},
    803:{"name":"符文图腾", "connected":[]},
    804:{"name":"鬼雾峰", "connected":[]},
    805:{"name":"黑暗之矛", "connected":[]},
    806:{"name":"红龙女王", "connected":[]},
    807:{"name":"红云台地", "connected":[]},
    808:{"name":"黄金之路", "connected":[]},
    810:{"name":"火羽山", "connected":[]},
    812:{"name":"迦罗娜", "connected":[]},
    814:{"name":"凯恩血蹄", "connected":[]},
    815:{"name":"狂风峭壁", "connected":[]},
    816:{"name":"雷斧堡垒", "connected":[]},
    817:{"name":"雷克萨", "connected":[]},
    818:{"name":"雷霆号角", "connected":[]},
    822:{"name":"玛里苟斯", "connected":[]},
    825:{"name":"纳沙塔尔", "connected":[]},
    826:{"name":"诺兹多姆", "connected":[]},
    827:{"name":"普罗德摩", "connected":[]},
    828:{"name":"千针石林", "connected":[]},
    829:{"name":"燃烧之刃", "connected":[]},
    830:{"name":"萨尔", "connected":[]},
    833:{"name":"圣火神殿", "connected":[]},
    835:{"name":"甜水绿洲", "connected":[]},
    837:{"name":"沃金", "connected":[]},
    838:{"name":"熊猫酒仙", "connected":[]},
    839:{"name":"血牙魔王", "connected":[]},
    840:{"name":"勇士岛", "connected":[]},
    841:{"name":"羽月", "connected":[]},
    842:{"name":"蜘蛛王国", "connected":[]},
    843:{"name":"自由之风", "connected":[]},
    844:{"name":"阿尔萨斯", "connected":[]},
    845:{"name":"阿拉索", "connected":[]},
    846:{"name":"埃雷达尔", "connected":[]},
    847:{"name":"艾欧娜尔", "connected":[]},
    848:{"name":"安东尼达斯", "connected":[]},
    849:{"name":"暗影议会", "connected":[]},
    850:{"name":"奥特兰克", "connected":[]},
    851:{"name":"巴尔古恩", "connected":[]},
    852:{"name":"冰风岗", "connected":[]},
    855:{"name":"达隆米尔", "connected":[]},
    856:{"name":"耳语海岸", "connected":[]},
    857:{"name":"古尔丹", "connected":[]},
    858:{"name":"寒冰皇冠", "connected":[]},
    859:{"name":"基尔加丹", "connected":[]},
    860:{"name":"激流堡", "connected":[]},
    861:{"name":"巨龙之吼", "connected":[]},
    862:{"name":"暗影裂口", "connected":[]},
    863:{"name":"凯尔萨斯", "connected":[]},
    864:{"name":"克尔苏加德", "connected":[]},
    865:{"name":"拉格纳罗斯", "connected":[]},
    866:{"name":"埃霍恩", "connected":[]},
    867:{"name":"利刃之拳", "connected":[]},
    869:{"name":"玛诺洛斯", "connected":[]},
    870:{"name":"麦迪文", "connected":[]},
    872:{"name":"耐奥祖", "connected":[]},
    874:{"name":"瑞文戴尔", "connected":[]},
    876:{"name":"霜狼", "connected":[]},
    877:{"name":"霜之哀伤", "connected":[]},
    878:{"name":"斯坦索姆", "connected":[]},
    879:{"name":"塔伦米尔", "connected":[]},
    882:{"name":"提瑞斯法", "connected":[]},
    883:{"name":"通灵学院", "connected":[]},
    885:{"name":"希尔瓦娜斯", "connected":[]},
    886:{"name":"血色十字军", "connected":[]},
    887:{"name":"遗忘海岸", "connected":[]},
    888:{"name":"银松森林", "connected":[]},
    889:{"name":"银月", "connected":[]},
    890:{"name":"鹰巢山", "connected":[]},
    891:{"name":"影牙要塞", "connected":[]},
    915:{"name":"狂热之刃", "connected":[]},
    916:{"name":"卡珊德拉", "connected":[]},
    917:{"name":"迅捷微风", "connected":[]},
    918:{"name":"守护之剑", "connected":[]},
    920:{"name":"斩魔者", "connected":[]},
    921:{"name":"布兰卡德", "connected":[]},
    922:{"name":"世界之树", "connected":[]},
    924:{"name":"恶魔之翼", "connected":[]},
    925:{"name":"万色星辰", "connected":[]},
    926:{"name":"激流之傲", "connected":[]},
    927:{"name":"加兹鲁维", "connected":[]},
    929:{"name":"苏塔恩", "connected":[]},
    930:{"name":"大地之怒", "connected":[]},
    931:{"name":"雏龙之翼", "connected":[]},
    932:{"name":"黑暗魅影", "connected":[]},
    933:{"name":"踏梦者", "connected":[]},
    938:{"name":"密林游侠", "connected":[]},
    940:{"name":"伊森利恩", "connected":[]},
    941:{"name":"神圣之歌", "connected":[]},
    943:{"name":"暮色森林", "connected":[]},
    944:{"name":"元素之力", "connected":[]},
    946:{"name":"日落沼泽", "connected":[]},
    949:{"name":"芬里斯", "connected":[]},
    951:{"name":"伊萨里奥斯", "connected":[]},
    953:{"name":"风暴之眼", "connected":[]},
    954:{"name":"提尔之手", "connected":[]},
    956:{"name":"永夜港", "connected":[]},
    959:{"name":"朵丹尼尔", "connected":[]},
    960:{"name":"法拉希姆", "connected":[]},
    962:{"name":"金色平原", "connected":[]},
    980:{"name":"天空之牆", "connected":[]},
    1198:{"name":"安其拉", "connected":[]},
    1199:{"name":"安纳塞隆", "connected":[]},
    1200:{"name":"阿努巴拉克", "connected":[]},
    1201:{"name":"阿拉希", "connected":[]},
    1202:{"name":"瓦里玛萨斯", "connected":[]},
    1203:{"name":"巴纳扎尔", "connected":[]},
    1204:{"name":"黑手军团", "connected":[]},
    1205:{"name":"血羽", "connected":[]},
    1206:{"name":"燃烧军团", "connected":[]},
    1207:{"name":"克洛玛古斯", "connected":[]},
    1208:{"name":"破碎岭", "connected":[]},
    1209:{"name":"克苏恩", "connected":[]},
    1210:{"name":"阿纳克洛斯", "connected":[]},
    1211:{"name":"雷霆之怒", "connected":[]},
    1212:{"name":"桑德兰", "connected":[]},
    1213:{"name":"黑翼之巢", "connected":[]},
    1214:{"name":"德拉诺", "connected":[]},
    1215:{"name":"龙骨平原", "connected":[]},
    1216:{"name":"卡拉赞", "connected":[]},
    1221:{"name":"熔火之心", "connected":[]},
    1222:{"name":"格瑞姆巴托", "connected":[]},
    1223:{"name":"古拉巴什", "connected":[]},
    1224:{"name":"哈卡", "connected":[]},
    1225:{"name":"海克泰尔", "connected":[]},
    1226:{"name":"库尔提拉斯", "connected":[]},
    1227:{"name":"洛丹伦", "connected":[]},
    1228:{"name":"奈法利安", "connected":[]},
    1229:{"name":"奎尔萨拉斯", "connected":[]},
    1230:{"name":"拉贾克斯", "connected":[]},
    1231:{"name":"拉文霍德", "connected":[]},
    1232:{"name":"森金", "connected":[]},
    1233:{"name":"范达尔鹿盔", "connected":[]},
    1234:{"name":"泰拉尔", "connected":[]},
    1235:{"name":"瓦拉斯塔兹", "connected":[]},
    1236:{"name":"永恒之井", "connected":[]},
    1237:{"name":"海达希亚", "connected":[]},
    1238:{"name":"萨菲隆", "connected":[]},
    1239:{"name":"纳克萨玛斯", "connected":[]},
    1240:{"name":"无尽之海", "connected":[]},
    1241:{"name":"莱索恩", "connected":[]},
    1482:{"name":"阿卡玛", "connected":[]},
    1483:{"name":"阿扎达斯", "connected":[]},
    1484:{"name":"灰谷", "connected":[]},
    1485:{"name":"艾维娜", "connected":[]},
    1486:{"name":"巴瑟拉斯", "connected":[]},
    1487:{"name":"血顶", "connected":[]},
    1488:{"name":"恐怖图腾", "connected":[]},
    1489:{"name":"古加尔", "connected":[]},
    1490:{"name":"达文格尔", "connected":[]},
    1491:{"name":"黑铁", "connected":[]},
    1492:{"name":"恶魔之魂", "connected":[]},
    1493:{"name":"迪瑟洛克", "connected":[]},
    1494:{"name":"丹莫德", "connected":[]},
    1495:{"name":"艾莫莉丝", "connected":[]},
    1496:{"name":"埃克索图斯", "connected":[]},
    1497:{"name":"菲拉斯", "connected":[]},
    1498:{"name":"加基森", "connected":[]},
    1499:{"name":"加里索斯", "connected":[]},
    1500:{"name":"格雷迈恩", "connected":[]},
    1501:{"name":"布莱恩", "connected":[]},
    1502:{"name":"伊莫塔尔", "connected":[]},
    1503:{"name":"大漩涡", "connected":[]},
    1504:{"name":"诺森德", "connected":[]},
    1505:{"name":"奥妮克希亚", "connected":[]},
    1506:{"name":"奥斯里安", "connected":[]},
    1507:{"name":"外域", "connected":[]},
    1508:{"name":"天空之墙", "connected":[]},
    1509:{"name":"风暴之鳞", "connected":[]},
    1510:{"name":"荆棘谷", "connected":[]},
    1511:{"name":"逐日者", "connected":[]},
    1512:{"name":"塔纳利斯", "connected":[]},
    1513:{"name":"瑟莱德丝", "connected":[]},
    1514:{"name":"塞拉赞恩", "connected":[]},
    1515:{"name":"托塞德林", "connected":[]},
    1516:{"name":"黑暗虚空", "connected":[]},
    1517:{"name":"安戈洛", "connected":[]},
    1519:{"name":"祖尔金", "connected":[]},
    1520:{"name":"双子峰", "connected":[]},
    1524:{"name":"天谴之门", "connected":[]},
    1657:{"name":"冰川之拳", "connected":[]},
    1658:{"name":"刺骨利刃", "connected":[]},
    1659:{"name":"深渊之巢", "connected":[]},
    1660:{"name":"埃基尔松", "connected":[]},
    1662:{"name":"火烟之谷", "connected":[]},
    1663:{"name":"伊兰尼库斯", "connected":[]},
    1664:{"name":"火喉", "connected":[]},
    1666:{"name":"冬寒", "connected":[]},
    1667:{"name":"迦玛兰", "connected":[]},
    1668:{"name":"金度", "connected":[]},
    1670:{"name":"巫妖之王", "connected":[]},
    1672:{"name":"米奈希尔", "connected":[]},
    1676:{"name":"幽暗沼泽", "connected":[]},
    1681:{"name":"烈焰荆棘", "connected":[]},
    1682:{"name":"夺灵者", "connected":[]},
    1685:{"name":"石锤", "connected":[]},
    1687:{"name":"塞拉摩", "connected":[]},
    1692:{"name":"厄祖玛特", "connected":[]},
    1693:{"name":"冬泉谷", "connected":[]},
    1694:{"name":"伊森德雷", "connected":[]},
    1695:{"name":"扎拉赞恩", "connected":[]},
    1696:{"name":"亚雷戈斯", "connected":[]},
    1793:{"name":"深渊之喉", "connected":[]},
    1794:{"name":"凤凰之神", "connected":[]},
    1795:{"name":"阿古斯", "connected":[]},
    1796:{"name":"奥金顿", "connected":[]},
    1797:{"name":"刀塔", "connected":[]},
    1798:{"name":"鲜血熔炉", "connected":[]},
    1801:{"name":"黑暗之门", "connected":[]},
    1802:{"name":"死亡熔炉", "connected":[]},
    1803:{"name":"无底海渊", "connected":[]},
    1807:{"name":"格鲁尔", "connected":[]},
    1808:{"name":"哈兰", "connected":[]},
    1809:{"name":"军团要塞", "connected":[]},
    1810:{"name":"麦姆", "connected":[]},
    1812:{"name":"艾露恩", "connected":[]},
    1813:{"name":"穆戈尔", "connected":[]},
    1815:{"name":"摩摩尔", "connected":[]},
    1817:{"name":"试炼之环", "connected":[]},
    1818:{"name":"罗曼斯", "connected":[]},
    1819:{"name":"希雷诺斯", "connected":[]},
    1820:{"name":"塞泰克", "connected":[]},
    1821:{"name":"暗影迷宫", "connected":[]},
    1823:{"name":"托尔巴拉德", "connected":[]},
    1824:{"name":"太阳之井", "connected":[]},
    1827:{"name":"末日祷告祭坛", "connected":[]},
    1828:{"name":"范克里夫", "connected":[]},
    1829:{"name":"瓦丝琪", "connected":[]},
    1830:{"name":"祖阿曼", "connected":[]},
    1831:{"name":"祖达克", "connected":[]},
    1832:{"name":"翡翠梦境", "connected":[]},
    1931:{"name":"阿比迪斯", "connected":[]},
    1932:{"name":"阿曼尼", "connected":[]},
    1933:{"name":"安苏", "connected":[]},
    1934:{"name":"生态船", "connected":[]},
    1935:{"name":"阿斯塔洛", "connected":[]},
    1936:{"name":"白骨荒野", "connected":[]},
    1937:{"name":"布鲁塔卢斯", "connected":[]},
    1938:{"name":"达尔坎", "connected":[]},
    1939:{"name":"末日行者", "connected":[]},
    1940:{"name":"达基萨斯", "connected":[]},
    1941:{"name":"熵魔", "connected":[]},
    1942:{"name":"能源舰", "connected":[]},
    1943:{"name":"菲米丝", "connected":[]},
    1944:{"name":"加尔", "connected":[]},
    1945:{"name":"迦顿", "connected":[]},
    1946:{"name":"血吼", "connected":[]},
    1947:{"name":"戈提克", "connected":[]},
    1948:{"name":"盖斯", "connected":[]},
    1949:{"name":"壁炉谷", "connected":[]},
    1950:{"name":"贫瘠之地", "connected":[]},
    1955:{"name":"霍格", "connected":[]},
    1965:{"name":"奎尔丹纳斯", "connected":[]},
    1969:{"name":"萨洛拉丝", "connected":[]},
    1970:{"name":"沙怒", "connected":[]},
    1971:{"name":"嚎风峡湾", "connected":[]},
    1972:{"name":"斯克提斯", "connected":[]},
    2118:{"name":"迦拉克隆", "connected":[]},
    2119:{"name":"奥杜尔", "connected":[]},
    2120:{"name":"奥尔加隆", "connected":[]},
    2121:{"name":"安格博达", "connected":[]},
    2122:{"name":"安加萨", "connected":[]},
    2123:{"name":"织亡者", "connected":[]},
    2124:{"name":"亡语者", "connected":[]},
    2125:{"name":"达克萨隆", "connected":[]},
    2126:{"name":"黑锋哨站", "connected":[]},
    2127:{"name":"古达克", "connected":[]},
    2128:{"name":"兰娜瑟尔", "connected":[]},
    2129:{"name":"洛肯", "connected":[]},
    2130:{"name":"玛洛加尔", "connected":[]},
    2133:{"name":"影之哀伤", "connected":[]},
    2134:{"name":"风暴峭壁", "connected":[]},
    2135:{"name":"远古海滩", "connected":[]},
    2136:{"name":"瓦拉纳", "connected":[]},
    2137:{"name":"冬拥湖", "connected":[]},
    3751:{"name":"丽丽（四川）", "connected":[]},
    3752:{"name":"晴日峰（江苏）", "connected":[]},
    3755:{"name":"辛达苟萨", "connected":[]},
    3757:{"name":"时光之穴", "connected":[]},
    3941:{"name":"苏拉玛", "connected":[]},
    3944:{"name":"瓦里安", "connected":[]},
    4497:{"name":"碧玉矿洞", "connected":[]},
    4498:{"name":"寒脊山小径", "connected":[]},
    4499:{"name":"埃提耶什", "connected":[]},
    4500:{"name":"龙之召唤", "connected":[]},
    4501:{"name":"加丁", "connected":[]},
    4509:{"name":"哈霍兰", "connected":[]},
    4510:{"name":"奥罗", "connected":[]},
    4511:{"name":"沙尔图拉", "connected":[]},
    4512:{"name":"莫格莱尼", "connected":[]},
    4513:{"name":"希尔盖", "connected":[]},
    4520:{"name":"匕首岭", "connected":[]},
    4521:{"name":"厄运之槌", "connected":[]},
    4522:{"name":"雷霆之击", "connected":[]},
    4523:{"name":"法尔班克斯", "connected":[]},
    4524:{"name":"赫洛德", "connected":[]},
    4531:{"name":"布鲁", "connected":[]},
    4532:{"name":"范克瑞斯", "connected":[]},
    4533:{"name":"维希度斯", "connected":[]},
    4534:{"name":"帕奇维克", "connected":[]},
    4535:{"name":"比格沃斯", "connected":[]},
    4675:{"name":"辛迪加", "connected":[]},
    4707:{"name":"霜语", "connected":[]},
    4708:{"name":"水晶之牙", "connected":[]},
    4709:{"name":"维克洛尔", "connected":[]},
    4710:{"name":"维克尼拉斯", "connected":[]},
    4711:{"name":"巴罗夫", "connected":[]},
    4712:{"name":"比斯巨兽", "connected":[]},
    4767:{"name":"诺格弗格", "connected":[]},
    4768:{"name":"毁灭之刃", "connected":[]},
    4769:{"name":"黑曜石之锋", "connected":[]},
    4770:{"name":"萨弗拉斯", "connected":[]},
    4771:{"name":"伦鲁迪洛尔", "connected":[]},
    4772:{"name":"灰烬使者", "connected":[]},
    4773:{"name":"怀特迈恩", "connected":[]},
    4774:{"name":"奥金斧", "connected":[]},
    4775:{"name":"骨火", "connected":[]},
    4776:{"name":"末日之刃", "connected":[]},
    4777:{"name":"震地者", "connected":[]},
    4778:{"name":"祈福", "connected":[]},
    4779:{"name":"辛洛斯", "connected":[]},
    4780:{"name":"觅心者", "connected":[]},
    4781:{"name":"狮心", "connected":[]},
    4782:{"name":"审判", "connected":[]},
    4783:{"name":"无尽风暴", "connected":[]},
    4784:{"name":"巨龙追猎者", "connected":{ }},
    4785:{"name":"灵风", "connected":[]},
    4786:{"name":"卓越", "connected":[]},
    4787:{"name":"狂野之刃", "connected":[]},
    4788:{"name":"巨人追猎者", "connected":[]},
    4789:{"name":"秩序之源", "connected":[]},
    4790:{"name":"奎尔塞拉", "connected":[]},
    4791:{"name":"碧空之歌", "connected":[]},
    4818:{"name":"艾隆纳亚", "connected":[]},
    4819:{"name":"席瓦莱恩", "connected":[]},
    4820:{"name":"火锤", "connected":[]},
    4821:{"name":"沙顶", "connected":[]},
    4822:{"name":"德姆塞卡尔", "connected":[]},
    4824:{"name":"怒炉", "connected":[]},
    4827:{"name":"无畏", "connected":[]},
    4829:{"name":"安娜丝塔丽", "connected":[]},
    4832:{"name":"雷德", "connected":[]},
    4833:{"name":"曼多基尔", "connected":[]},
    4834:{"name":"娅尔罗", "connected":[]},
    4837:{"name":"范沃森", "connected":[]},
    4847:{"name":"光芒", "connected":[]},
    4913:{"name":"寒冰之王", "connected":[]},
    4920:{"name":"龙牙", "connected":[]},
    4924:{"name":"法琳娜", "connected":[]},
    4925:{"name":"湖畔镇", "connected":[]},
    4926:{"name":"克罗米", "connected":[]},
    4938:{"name":"无敌", "connected":[]},
    4939:{"name":"冰封王座", "connected":[]},
    4940:{"name":"巫妖王", "connected":[]},
    4941:{"name":"银色北伐军", "connected":[]},
    4942:{"name":"吉安娜", "connected":[]},
    4943:{"name":"死亡猎手", "connected":[]},
    4945:{"name":"红玉圣殿", "connected":[]},
    5735:{"name":"克羅之刃", "connected":[]},
}

# 创建一个 name 到 id 的映射
name_to_id = {data["name"]: id for id, data in realmData.items()}

# 遍历文件1的数据
for group in realms:
    for name in group:
        if name in name_to_id:
            current_id = name_to_id[name]
            for other_name in group:
                if other_name != name and other_name in name_to_id:
                    other_id = name_to_id[other_name]
                    realmData[current_id]["connected"].append(other_id)

# 将结果输出到文件
with open('output.lua', 'w', encoding='utf-8') as f:
    for id, data in realmData.items():
        if data['connected']:
            connected_str = ",".join(map(str, data['connected']))
            f.write(f"[{id}] = \"{data['name']},{connected_str}\",\n")
        else:
            f.write(f"[{id}] = \"{data['name']}\",\n")

print("结果已输出到 output.lua 文件中")